// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBpf_prog returns the embedded CollectionSpec for bpf_prog.
func loadBpf_prog() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Bpf_progBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf_prog: %w", err)
	}

	return spec, err
}

// loadBpf_progObjects loads bpf_prog and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpf_progObjects
//	*bpf_progPrograms
//	*bpf_progMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpf_progObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf_prog()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpf_progSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_progSpecs struct {
	bpf_progProgramSpecs
	bpf_progMapSpecs
	bpf_progVariableSpecs
}

// bpf_progProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_progProgramSpecs struct {
	MyProg *ebpf.ProgramSpec `ebpf:"my_prog"`
}

// bpf_progMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_progMapSpecs struct {
}

// bpf_progVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_progVariableSpecs struct {
}

// bpf_progObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpf_progObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_progObjects struct {
	bpf_progPrograms
	bpf_progMaps
	bpf_progVariables
}

func (o *bpf_progObjects) Close() error {
	return _Bpf_progClose(
		&o.bpf_progPrograms,
		&o.bpf_progMaps,
	)
}

// bpf_progMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpf_progObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_progMaps struct {
}

func (m *bpf_progMaps) Close() error {
	return _Bpf_progClose()
}

// bpf_progVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpf_progObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_progVariables struct {
}

// bpf_progPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpf_progObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_progPrograms struct {
	MyProg *ebpf.Program `ebpf:"my_prog"`
}

func (p *bpf_progPrograms) Close() error {
	return _Bpf_progClose(
		p.MyProg,
	)
}

func _Bpf_progClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_prog_bpfel.o
var _Bpf_progBytes []byte
