// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadXdp_count returns the embedded CollectionSpec for xdp_count.
func loadXdp_count() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Xdp_countBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp_count: %w", err)
	}

	return spec, err
}

// loadXdp_countObjects loads xdp_count and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdp_countObjects
//	*xdp_countPrograms
//	*xdp_countMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdp_countObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp_count()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdp_countSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_countSpecs struct {
	xdp_countProgramSpecs
	xdp_countMapSpecs
	xdp_countVariableSpecs
}

// xdp_countProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_countProgramSpecs struct {
	CountPackets *ebpf.ProgramSpec `ebpf:"count_packets"`
}

// xdp_countMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_countMapSpecs struct {
	PktCount *ebpf.MapSpec `ebpf:"pkt_count"`
}

// xdp_countVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_countVariableSpecs struct {
}

// xdp_countObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdp_countObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_countObjects struct {
	xdp_countPrograms
	xdp_countMaps
	xdp_countVariables
}

func (o *xdp_countObjects) Close() error {
	return _Xdp_countClose(
		&o.xdp_countPrograms,
		&o.xdp_countMaps,
	)
}

// xdp_countMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdp_countObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_countMaps struct {
	PktCount *ebpf.Map `ebpf:"pkt_count"`
}

func (m *xdp_countMaps) Close() error {
	return _Xdp_countClose(
		m.PktCount,
	)
}

// xdp_countVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdp_countObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_countVariables struct {
}

// xdp_countPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdp_countObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_countPrograms struct {
	CountPackets *ebpf.Program `ebpf:"count_packets"`
}

func (p *xdp_countPrograms) Close() error {
	return _Xdp_countClose(
		p.CountPackets,
	)
}

func _Xdp_countClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_count_bpfeb.o
var _Xdp_countBytes []byte
